language: "perl"
perl:
    - "5.10"
install: "echo"
before_script:
    - gcc --version
    - clang --version

script: "perl Configure.pl $MVM_OPTIONS --debug --optimize --cc=\"$CC\"; make install

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc: "irc.freenode.net#moarvm"

env:
  matrix:
    - MVM_OPTIONS="--enable-jit"  CC="gcc"
    - MVM_OPTIONS=""              CC="gcc"
    - MVM_OPTIONS="--enable-jit"  CC="clang"
    - MVM_OPTIONS=""              CC="clang"
